### ISSUE TITLE
MultiSigWallet

### ISSUE THREAD

**Issue by AnmolSirola** [metafy-social/web3-smart-contracts#100]
### Is your feature request related to a problem? Please describe.
 Making a  MultiSigWallet

### Describe the solution you'd like
MultiSigWallet is a allows users to receive and send tokens to different users, it is used by multiple people so in order to have a transaction all of the users should sign it

**Comment by advaita-saha** [comment]
@AnmolSirola it is already there

**Comment by AnmolSirola** [comment]
@advaita-saha Can you tell me something I can work on. I really wanna contribute here
