### ISSUE TITLE
Vaccine Tracker - Smart Contract

### ISSUE THREAD

**Issue by ShwetKhatri2001** [metafy-social/web3-smart-contracts#108]
### Is your feature request related to a problem? Please describe.
Tracking and distribution of the vaccine was a huge problem when we were facing a shortage of vaccines. Also, some distributors took advantage of non-transparent systems being handled by humans. A small mistake in tracking or providing the vaccine can lead someone to death. 

### Describe the solution you'd like
A smart contract can track the batch of vaccines like their registration, requirement in labs, confirmation of delivery and all these can be handled by approval of a single admin.

I'd like to add such smart contract.

**Comment by advaita-saha** [comment]
also give a NFT vaccine certificate, ERC-1155

**Comment by ShwetKhatri2001** [comment]
@advaita-saha I'm just trying to cover the distribution of vaccines to the center ( kind of B2B contract ). From the center to the patient is another long process to be tracked for which we can have a separate smart contract ( kind of B2C contract ).
