### ISSUE TITLE
Soulbound Token Contract

### ISSUE THREAD

**Issue by sayan011** [metafy-social/web3-smart-contracts#11]
### Is your feature request related to a problem? Please describe.
Write a contract for  Soulbound Token

### Describe the solution you'd like
create a file inside `contract/NFT/<your_filename.sol>
`(Refer [Here](https://eips.ethereum.org/EIPS/eip-5114#:~:text=A%20soulbound%20token%20is%20a,be%20transferred%2Fmoved%20after%20that.) if you don't know what Soulbound Token is)
### Please comment your approach towards this, and we are happy to assign this to you.

**Comment by adityabhattad2021** [comment]
I would like to complete this issue.

**Comment by advaita-saha** [comment]
@adityabhattad2021 Sure go ahead
