### ISSUE TITLE
Tic Tac Toe game - Smart Contract

### ISSUE THREAD

**Issue by Debopom-Banerjee** [metafy-social/web3-smart-contracts#111]
### Is your feature request related to a problem? Please describe.
A two player tic tac toe game managed with a smart contract.

### Describe the solution you'd like

There are 5 public attributes:

1. player1-indicate address of player1
2. player2 -indicate address of player2
3.  board- keep track of each player move and game state
4. whosTurn-indicate which player’s turn
5.  gameOver- function that check if game is over

I want to work on this issue, please assign me.

**Comment by advaita-saha** [comment]
@Debopom-Banerjee go ahead
