### ISSUE TITLE
Multisig Wallet

### ISSUE THREAD

**Issue by sayan011** [metafy-social/web3-smart-contracts#12]
### Is your feature request related to a problem? Please describe.
Create a simple Multisig Wallet

**Comment by adityabhattad2021** [comment]
I would like to complete this task.

**Comment by advaita-saha** [comment]
@adityabhattad2021 Go ahead

**Comment by aviral727** [comment]
Hey I would like to complete this task!

**Comment by advaita-saha** [comment]
> Hey I would like to complete this task!

Hey this is already assigned, you can create a new issue with a new idea which you would like to contribute

**Comment by adityabhattad2021** [comment]
I will make a pr by tomorrow...
