### ISSUE TITLE
Rock Paper Scissors Game - Smart Contract

### ISSUE THREAD

**Issue by ShwetKhatri2001** [metafy-social/web3-smart-contracts#121]
### Is your feature request related to a problem? Please describe.
An online two-player game can be managed with a smart contract.

### Describe the solution you'd like
A  smart contract that covers all the cases of input by two players, calculates the scores and announces the winner.

I'd like to add this game smart contract.

**Comment by 0xVikasRushi** [comment]
Hey I would like to contribute
