### ISSUE TITLE
Create a Faucet smart contract 

### ISSUE THREAD

**Issue by nirban256** [metafy-social/web3-smart-contracts#13]
### Describe the solution you'd like
I want to create a faucet smart contract for a specific ERC20 token where anybody will be able to get a certain amount of token from the contract's account to there account.

**Comment by advaita-saha** [comment]
Sure go ahead

**Comment by nirban256** [comment]
Is this repository is present under hacktoberfest? @advaita-saha

**Comment by advaita-saha** [comment]
Yess @nirban256 
We also do have NFT reward for all contributors as mentioned above
And T-shirts also

Do follow the mentioned instructions for that

**Comment by nirban256** [comment]
thanks @advaita-saha
