### ISSUE TITLE
Want to create a Token

### ISSUE THREAD

**Issue by vishal14072002** [metafy-social/web3-smart-contracts#18]
### Is your feature request related to a problem? Please describe.
Token Creation

### Describe alternatives you've considered
Token Using Solidity
### Additional context
It will be created on remix ide

**Comment by advaita-saha** [comment]
@vishal14072002 
please mention which type of token you want to create

**Comment by vishal14072002** [comment]
ERC20 Token

**Comment by advaita-saha** [comment]
It is already there
Please provide some additions over it or raise some different issue

**Comment by nitantchhajed** [comment]
> ERC20 Token
ERC20 Token Smart contract is already present in the repository. here is the link - https://github.com/metafy-social/web3-smart-contracts/blob/master/contracts/Coins/erc20std.sol

**Comment by Debopom-Banerjee** [comment]
hello @nitantchhajed can I contribute ERC721 Token Smart contract.

**Comment by advaita-saha** [comment]
it is already there @Debopom-Banerjee
