### ISSUE TITLE
Lending Borrowing Protocol Contract (DEFI)

### ISSUE THREAD

**Issue by vishesh0123** [metafy-social/web3-smart-contracts#21]
### Is your feature request related to a problem? Please describe.
Liquidity Protocol implementing Deposit , Borrow , Repay , Liquidation , Flashloan feature.

### Describe the solution you'd like
Simple AAVE based approach for implantation of this contract.

**Comment by advaita-saha** [comment]
@vishesh0123 sure go ahead

**Comment by vishesh0123** [comment]
> @vishesh0123 sure go ahead
assign this to me .

**Comment by advaita-saha** [comment]
@vishesh0123 updates??

**Comment by 0xVikasRushi** [comment]
@vishesh0123 are you working on it ? 
if not can you assign me this i would like to contribute!
