### ISSUE TITLE
Real Estate Property Contract

### ISSUE THREAD

**Issue by vish-han** [metafy-social/web3-smart-contracts#22]
### Is your feature request related to a problem? Please describe.
There are many fraud related to property papers that's happen.

### Describe the solution you'd like
a contract that to store the owner of the property on the blockchain.

**Comment by vish-han** [comment]
I would love to work on this issue.

**Comment by advaita-saha** [comment]
@vish-han Sure go ahead

**Comment by advaita-saha** [comment]
@vish-han updates??

**Comment by vish-han** [comment]
Was Sick for few days! Will make the PR today

**Comment by advaita-saha** [comment]
cool np, get well soon
