### ISSUE TITLE
To add detail guidelines for contribution in Readme.md

### ISSUE THREAD

**Issue by Kirankp25** [metafy-social/web3-smart-contracts#26]
### Is your feature request related to a problem? Please describe.
 To add detail about every step towards contribution to make it accessible to beginners of open source contributors

### Describe the solution you'd like
I will put every step of my contribution 

### Describe alternatives you've considered
you can put a link of detail guidelines but feel not good to the contributor

### Additional context
yes defiantly but before that assign me this issue, and then I will work on it and I will send the screenshot of the new changes

**Comment by advaita-saha** [comment]
Sorry we are not taking documentation issues in this repo for Hacktoberfest @Kirankp25
