### ISSUE TITLE
Ecommerce Smart Contract

### ISSUE THREAD

**Issue by guha-rahul** [metafy-social/web3-smart-contracts#27]
### Is your feature request related to a problem? Please describe.
Creation of a smart contract that acts a the Decentralised backend of an simple ecommerce website.

### Describe the solution you'd like
There will be provision for a seller to register his product and the buyer to buy the product using ETH.

- using struct to register the product.
- making a payable function for the smart contract to accept ether.
- Upon delivery, a delivery function must be executed for the seller to receiver their ether.

**Comment by guha-rahul** [comment]
May i work on this?

**Comment by advaita-saha** [comment]
@guha-rahul sure
