### ISSUE TITLE
Voting System Smart-Contract

### ISSUE THREAD

**Issue by advaita-saha** [metafy-social/web3-smart-contracts#3]
### Is your feature request related to a problem? Please describe
A trustless voting system to be designed, which can work better than the current voting machine, leveraging the power of blockchain technology

### Describe the solution you'd like
Use solidity, to create a contract
Create a folder for your entire project if you want

**Comment by karanpatel2329** [comment]
I am willing to work on it. Please assign to me

**Comment by advaita-saha** [comment]
Ok sure go ahead @karanpatel2329 
Do comment your approach here once

**Comment by agnxsh** [comment]
@karanpatel2329 a screen recording of your contract testing and deployment will be much appreciated too!

**Comment by karanpatel2329** [comment]
yes, I will add screen recording with PR.
