### ISSUE TITLE
NFT Drop registration - Smart Contract

### ISSUE THREAD

**Issue by ShwetKhatri2001** [metafy-social/web3-smart-contracts#33]
### Is your feature request related to a problem? Please describe.
The NFT drop registration needs to be automated.

### Describe the solution you'd like
I want to add a smart contract that allows users to register their NFT drop.

@advaita-saha I'd like to work on this task. Please assign it to me.

**Comment by advaita-saha** [comment]
Please elaborate what you want to achieve

**Comment by ShwetKhatri2001** [comment]
NFT Drop refers to a digital event where an NFT collection is released to the public for the purpose of sale or promotion. I want to create a contract that can add an NFT with all its metadata such as name, description, price, URLs, sale, etc to the NFT droplist. An owner will have privileges to add, update, remove an NFT and manage its visibility in public.

**Comment by ShwetKhatri2001** [comment]
@advaita-saha I think it's worth contributing, let me know your thoughts.

**Comment by advaita-saha** [comment]
@sayan011 please have a look

**Comment by sayan011** [comment]
@ShwetKhatri2001  Go ahead then....looking forward to your PR!
