### ISSUE TITLE
Smart contract for password storage on blockchain

### ISSUE THREAD

**Issue by rajdip-b** [metafy-social/web3-smart-contracts#34]
### Is your feature request related to a problem? Please describe.
Passwords can be easily forgotten. With increasing cyberattacks, strong passwords (preferably random passwords) are more and more in demand. Storing such passwords locally means unreliability, while storing them in some centralized infrastructure means security issues.

### Describe the solution you'd like
Create a smart contract that stores passwords on the blockchain under a specific wallet address.

### Describe alternatives you've considered
Creating web app that stores these passwords in local storage, which is, again, unreliable.

**Comment by advaita-saha** [comment]
@rajdip-b sure go ahead
