### ISSUE TITLE
smart contract for securing patient records on blockchain

### ISSUE THREAD

**Issue by issa-me-sush** [metafy-social/web3-smart-contracts#35]
### Is your feature request related to a problem? Please describe.
The issue is surrounding the  lack of control over patient data by the patients themselves, currently all conventional hospitals/medical institutes have  complete control over the  patient data , including access and storage, at times they even sell it to make profit out of medical and personal data, to prevent such incidents and give back control to the user  over their sensitive data, we need  to move to the web3 model of smart contracts/ decentralize storage of data.

### Describe the solution you'd like
We could start with working on a solidity smart contract that could store the patient data , and then  build functions on them, to add records/delete or modify records/give access to specific contract addresses to view the records or revoke it, fetch different fields or data.

### Describe alternatives you've considered
switching to cheaper blockchains or maybe a custom blockchain built on hyperledger to meet the same goals  with cheaper trx/network fees .

**Comment by advaita-saha** [comment]
@issa-me-sush go ahead

**Comment by advaita-saha** [comment]
@issa-me-sush updates??

**Comment by issa-me-sush** [comment]
will push the initial contract today, sorry for the delay!
