### ISSUE TITLE
Auction smart contract

### ISSUE THREAD

**Issue by nitantchhajed** [metafy-social/web3-smart-contracts#38]
### Is your feature request related to a problem? Please describe.
it will make auctions possible with the help of crypto payments.

### Additional context
Everyone can send their bids during a bidding period. The bids already include sending Ether in order to bind the bidders to their bid. If the highest bid is raised, the previous highest bidder gets their money back. After the end of the bidding period, the contract has to be called manually for the beneficiary to receive their money - contracts cannot activate themselves.

**Comment by nitantchhajed** [comment]
I would like to work on this Issue

**Comment by advaita-saha** [comment]
go ahead @nitantchhajed
