### ISSUE TITLE
Crowdfunding Smart Contract

### ISSUE THREAD

**Issue by kriptonian1** [metafy-social/web3-smart-contracts#4]
### Is your feature request related to a problem? Please describe. 
Bring the power back to the crowd, create a decentralized crowdfunding system. 

### Describe the solution you'd like
Use solidity to create crowdfunding contract
create a separate folder for the project

**Comment by 0xVikasRushi** [comment]
Hey! I would like to contribute this project
My approach 

- Register function 
  where owner of deploy contract with timestamp , contributor address , goal set 
- Contribute function
  where people can contribute with min amount set
- GoalCompleted function
  when goal is completed money will transfer to victim address (victim address!=owner address)
- Money Contributed
   returns a total money contributed


Please suggest any changes  i will start working on this

**Comment by advaita-saha** [comment]
Sure go ahead @0xVikasRushi 
If possible enclose the contract in factory pattern, where a new contract can be deployed for a particular crowd-funding event

**Comment by 0xVikasRushi** [comment]
Yeah I will try to enclose in factory pattern @advaita-saha 😁
