### ISSUE TITLE
Lottery Smart Contract

### ISSUE THREAD

**Issue by Debopom-Banerjee** [metafy-social/web3-smart-contracts#41]
### Is your feature request related to a problem? Please describe.
A smart contract that acts as a decentralized backend of a Lottery using Solidity.

### Describe the solution you'd like

-  Writing, Deploying and Testing our code using the remix editor.
-  Sending and receiving ETH.
-  Random and pseudo-number generation.

**Comment by advaita-saha** [comment]
@Debopom-Banerjee it is already present in the repo

**Comment by Debopom-Banerjee** [comment]
Sorry for the inconvenience.
