### ISSUE TITLE
NFT Royalties - Smart Contract

### ISSUE THREAD

**Issue by tsunami03** [metafy-social/web3-smart-contracts#47]
### Is your feature request related to a problem? Please describe.
Want to research and work on implementing an ERC-2981 (NFT Royalty Standard) Smart contract. It is a standard contract that works towards decentralizing the concept of paying artists the royalty that they are due when their art is used, for example, musicians when their music is used in films, streaming, etc. 

### Describe the solution you'd like
https://trufflesuite.com/guides/nft-royalty/ <br> Want to understand and work on the functions on this.

**Comment by advaita-saha** [comment]
Great choice @tsunami03 
Go ahead, best of luck

**Comment by advaita-saha** [comment]
@tsunami03 updates??
