### ISSUE TITLE
ERC-1155 NFT contract

### ISSUE THREAD

**Issue by advaita-saha** [metafy-social/web3-smart-contracts#5]
### Is your feature request related to a problem? Please describe
Create a ERC-1155 standard NFT

### Describe the solution you'd like
create a file inside `contract/NFT/<your_filename.sol>`
Implement the standard logic, and feel free to add your customisation, without violating the standards.

**Comment by adityabhattad2021** [comment]
Should I push to master branch itself, and make a PR?

**Comment by adityabhattad2021** [comment]
You can assign this to me.

**Comment by advaita-saha** [comment]
Sure go ahead @adityabhattad2021

**Comment by advaita-saha** [comment]
> Should I push to master branch itself, and make a PR?

Yess @adityabhattad2021
