### ISSUE TITLE
smart contract for restaurants

### ISSUE THREAD

**Issue by SunilPatel43** [metafy-social/web3-smart-contracts#59]
### Is your feature request related to a problem? Please describe.
The restaurant's data like reviews, and ratings are crucial for someone picking up the restaurant. There should not be any scope of mistakes.

### Describe the solution you'd like
A smart contract can save this information such as ratings, reviews, and bills. Also, it can provide different roles to view and modify things.

I'd like to work on this issue.

**Comment by advaita-saha** [comment]
go ahead @SunilPatel43
