### ISSUE TITLE
Ticketing system (ticket issue system)

### ISSUE THREAD

**Issue by kriptonian1** [metafy-social/web3-smart-contracts#6]
### Is your feature request related to a problem? Please describe.
We want a decentralized ticketing system where people will be able to book a ticket and the host can verify it once and no ticket forging can take place.

### Describe the solution you'd like
Use solidity, to create a contract
Create a folder for your entire project if you want

**Comment by tsunami03** [comment]
Hi! I am a beginner in Solidity but I would like to contribute to the project. Kindly take a look at my approach:

**Comment by tsunami03** [comment]
Hi, I'm a beginner, but I have a basic approach in mind and am willing to work on this issue. 

- An immutable address variable Host that gets initialized by a constructor function that assigns the Host as the msg.sender. 
- A public variable currentTicketID initialised as 1 at the time of deployment
- A mapping uint256 -> address that maps a ticketID to a single address
- buyTicket() / a public, payable function that on being called, maps the current ticket id to the msg.sender (payer) and increments the currentTicketID
- buyTicket() may also have a require function for paid value (msg.value) to be the ticket price only 
-  a modifier onlyHost (to let only the Host call a function)
- a function verifyTicket with parameters (ticket_id, claimer) with the onlyHost modifier that checks whether the mapping of the ticket_id is to the claimer and returns true/false accordingly
- receive(), fallback() external payable functions that calls the buyTicket() function

Kindly let me know if I can improve the above in any way. Thank you!

**Comment by advaita-saha** [comment]
@tsunami03  Go ahead

**Comment by tsunami03** [comment]
Hi @advaita-saha. I'm using a chainlink library for the project. It works fine on remix but locally the VS code dependencies are required. Could you guide me on how to install it? npm command isn't working.

**Comment by advaita-saha** [comment]
Sure let me have a look

**Comment by advaita-saha** [comment]
Try now
- `git pull`
- then try to compile your contract

**Comment by advaita-saha** [comment]
@tsunami03 updates??

**Comment by tsunami03** [comment]
@advaita-saha Hi! I'm so sorry for the late reply. I was out of town with no internet connectivity. I have tried it now, and the checks have been passed. Please review my pull request for the same and let me know if there are any changes I can make. Thank you
