### ISSUE TITLE
Escrow Contract

### ISSUE THREAD

**Issue by advaita-saha** [metafy-social/web3-smart-contracts#66]
### Describe the solution you'd like
Create a simple escrow contract

**Comment by JuanitaCathy** [comment]
Could i try?

**Comment by advaita-saha** [comment]
@JuanitaCathy sure go ahead

**Comment by advaita-saha** [comment]
This issue is open for anyone to take-up

**Comment by tsunami03** [comment]
Please assign it to me.

**Comment by advaita-saha** [comment]
@tsunami03 sure go ahead

**Comment by advaita-saha** [comment]
Don't forget this

Please add your email and metamask using the authentication link
Or else we won't be able to send you the amazing rewards you deserve

https://hacktoberfest.auth.metafy.social/

**Comment by tsunami03** [comment]
Hi @advaita-saha, I had done my authentication during the first PR itself, should I be doing it for every PR? Thanks for assigning the issue, btw.

**Comment by advaita-saha** [comment]
> Hi @advaita-saha, I had done my authentication during the first PR itself, should I be doing it for every PR? Thanks for assigning the issue, btw.

No just reminding people
Today we found a lot of people did not, that's why,
No harm in a small reminder

**Comment by tsunami03** [comment]
Okay I see. Thanks for the reminder!
