### ISSUE TITLE
Supply chain management

### ISSUE THREAD

**Issue by advaita-saha** [metafy-social/web3-smart-contracts#68]
### Is your feature request related to a problem? Please describe.
Supply chain from manufacturer to the consumer gets a lot of messed up. 

### Describe the solution you'd like
Create a smart contract so that the whole process can be seamless and no one can alter the data

### Please comment down below to take up this issue

**Comment by Dhanush-2605** [comment]
hi @advaita-saha can you assign it to me?

**Comment by advaita-saha** [comment]
@Dhanush-2605 go ahead

**Comment by Dhanush-2605** [comment]
ok, thank you
