### ISSUE TITLE
Salary Payment System ( Bulk Transfer )

### ISSUE THREAD

**Issue by advaita-saha** [metafy-social/web3-smart-contracts#7]
### Is your feature request related to a problem? Please describe.
Create a salary payment and monitoring smart-contract which can pay employees salary in bulk at a particular time of the month, with minimal gas fees.

### Describe the solution you'd like
Please use the concept of bulk-transfer, use `block.timestamp` to monitor timely release of payments, and penalty to employer if salary is not funded

**Comment by 0xVikasRushi** [comment]
Hey! I would like to contribute 

- struct to create   employee name, address, and salary and storing via mapping
- On deploy contracting note a block.timestamp 
- FOR EVERY MONTH Unix units  = average month is 30.42 days * 24 hrs * 60 sec (2628288)
- current block.timestamp - initial month timestamp  >= 2628288
- and changing initial month block.timestamp to current time
- then transferring  money employee address

**Comment by advaita-saha** [comment]
@0xVikasRushi 
Correct approach, 
Do try to implement penalty if the employer doesn't keep the contract funded for employees

**Comment by 0xVikasRushi** [comment]
Yeah !  I will add penalty feature  @advaita-saha

**Comment by advaita-saha** [comment]
@0xVikasRushi updates??

**Comment by 0xVikasRushi** [comment]
Yeah! need more 3 days it will be done. I was having sem exams previously

**Comment by advaita-saha** [comment]
Cool np, best of luck
