### ISSUE TITLE
Lottery Smart Contract

### ISSUE THREAD

**Issue by jaydeepdey03** [metafy-social/web3-smart-contracts#74]
### Is your feature request related to a problem? Please describe.
Every time the lottery “makes a new game” they have to spin up a ton of new paperwork, someone has to do the draw, people have to protect the integrity of the system

### Describe the solution you'd like
On blockchain, you don’t have to do any of that. You set the contract to run, and it automatically runs.

**Comment by advaita-saha** [comment]
@jaydeepdey03 already there
