### ISSUE TITLE
Smart Contract for storing comments(without spam) on blockchain

### ISSUE THREAD

**Issue by yes-im-harsh** [metafy-social/web3-smart-contracts#76]
### Is your feature request related to a problem? Please describe.
Developers like to show their projects to the public and expect genuine feedback regarding the projects, not spam messages.

### Describe the solution you'd like
Smart contract for storing messages and preventing spammers.

**Comment by yes-im-harsh** [comment]
@advaita-saha Please consider this issue. And add labels.

**Comment by advaita-saha** [comment]
go ahead @yes-im-harsh
