### ISSUE TITLE
Commit Reveal in solidity

### ISSUE THREAD

**Issue by supernovahs** [metafy-social/web3-smart-contracts#79]
### Is your feature request related to a problem? Please describe.
A minimal example showcasing commit reveal example in solidity
### Describe the solution you'd like
A new contract under the miscellaneous  folder with commit -reveal logic
### Additional context
Commit reveal is used to prove you know the decoded value of a certain data On Chain.

**Comment by advaita-saha** [comment]
@supernovahs go ahead
