### ISSUE TITLE
Time Lock Smart Contract

### ISSUE THREAD

**Issue by tsunami03** [metafy-social/web3-smart-contracts#94]
### Is your feature request related to a problem? Please describe.
The idea of locking funds in a crypto-wallet smart contracts has many applications. For example, the most common reason at the moment to lock funds would be to lock the invested funds by a team of investors to prevent any tokens from being cashed in and destabilizing the company straightaway. Moreover, there are applications like making a will, a pension or a trust fund based on this time-locking concept. 

### Describe the solution you'd like
Will try to implement a smart contract that time locks ERC20 tokens.

**Comment by advaita-saha** [comment]
@tsunami03 go ahead
